---
channel_ids:
  - UCzIO0iX4yKW2P4NkmmKq1PA
  - UChjRM_qQAaOAiLNbOGbYcRA
  - UC7C0GXPfKqP9mUE01MDfM_A
  - UCZWpT_0K2ExTIDnntKhwQTg
  - UCRy28FvxDXt9FfHIuqgvPBg
  - UCa76wbWueiRaHL858mXkvuw
  - UCoOae5nYA7VqaXzerajD0lg
  - UCLxT-YVIAR4F3dRHped9Dkg
  - UCC_NjLEb2Sley94py4vSYTA
  - UCgDqL4yzXb4BflimZaxL4Vg
  - UC-kFCSJLpxuJdgMnQz8Dvrg
  - UCVHFbqXqoYvEWM1Ddxl0QDg
  - UCEmOg9ooeiihAemFze-jQrg
  - UC9LFVFomQEpHyApyhlJoJIg
  - UCb2h-vtXFd5I-g8TFyOTXRA
  - UCTs3VX60I6EKrrwdkgrwCGQ
  - UCpYAQ8iVPlQwXWN7BE2chgQ 
  - UCtRSKEipM17PF7n0mi66btQ
  - UCpN4xx95-4aTpCLWOPNsuYg
  - UCvpfclapgcuJo0M_x65pfRw
  - UCdKvOz1yqCbty9TwmEUQSiA
  - UC06O4KRdg8OmbZzH3vb0GpA
  - UCaSM4GqhbaVmRT7fmmFmR1w
  - UCBX_-ls-dXuhFNSWSXcHrTA
  - UCUnPu9bBZGPjiPUN6IoA2LQ
  - UCyWZJKPmesjXMGDxR_nsAVQ
  - UCUq3Rn72jfQ-86CaCxj7XzA
  - UC5pYFm-URhNRRvtC5K8I5hA
  - UCxb2ktvayRwCIN9kBKgxUiQ
  - UCT09qC2vwlbJvofZRIdLalg
  - UC_Mv2BsvWR03-s7S5CrNm3w
  - UC_RovKmk0OCbuZjA8f08opw
  - UCjgpFI5dU-D1-kh9H1muoxQ
  - UCuVLXPqY4LZx3VgiXPmxkaQ
  - UCCSwbTR-seWT2cn9nVMp2Fw
  - UCqjVP9gAanUGFgTA5BRDvyA
  - UCbbrRNSQ2PzEp4OWUA3vSQQ
  - UCOTCtz0funVMzbuvxN_MXYA
  - UCR-DXc1voovS8nhAvccRZhg
  - UCwAnu01qlnVg1Ai2AbtTMaA
  - UCenU8Lc_KuRTyJzs0t1Tteg 
  - UCsCex8aMDs2b39TS_49Mpcg
  - UCaP1PNnr055fOt89JPry51w
  - UCBj7lf9bAmctuhsnZ3oxqsg
  - UC8p19gUXJYTsUPEpusHgteQ
  - UCAZ_PQn4RzFh5hapKE_qoOw
  - UCXuqSBlHAE6Xw-yeJA0Tunw
  - UCcdoCX9WJZZrhXHmpvhgc7A
  - UCBJycsmduvYEL83R_U4JriQ
  - UCpdZovh0BSPU6ViyFGWqgmA
  - UChpleBmo18P08aKCIgti38g
  - UC51UPs8iqgC6ugVROBcUQEQ
  - UCGfluwZUeQNG5HvHuKfSKgw
  - UCwBV-eg1dAkzrdjqJfyEj0w
  - UCuVLXPqY4LZx3VgiXPmxkaQ
  - UCMiJRAwDNSNzuYeN2uWa0pA
  - UCSuHzQ3GrHSzoBbwrIq3LLA
  - UC9x0AN7BWHpCDHSm9NiJFJQ
  - UCzcRQ3vRNr6fJ1A9rqFn7QA
  - UCYLnawaM-36HncBBUeWrlGA
  - UCO_vmeInQm5Z6dEZ6R5Kk0A
  - UCwOBG77Tm8cE24FPxHb_abw
  - UCnvqF2-dOB9qo9EPDHRX9mg
  - UCKlOmM_eB0nzTNiDFZibSSA
  - UC_1awbvccFZOnVRjAIkCG7Q
  - UC2iUwfYi_1FCGGqhOUNx-iA
  - UCwOBG77Tm8cE24FPxHb_abw
  - UCO2x-p9gg9TLKneXlibGR7w
  - UCllfWlBHBvMmkiz15S8bCqw
  - UCg_Li5b7mfzM_NDUw4hQn6w
  - UCjMVmz06abZGVdWjd1mAMnQ
  - UC-bIwzgXdR4mThJfRQNkyCw
  - UCIfBYTbPSg_Pj1i5V8WyBxg
  - UC-2EdaIT69qmIB4fLppdG0Q
  - UCJabiIk1qnY_4oCbEmeOdxA
  - UC2gyzKcHbYfqoXA5xbyGXtQ
  - UCQEuTSzPFeN84a0JhhF-QFQ
  - UCV6lt7Sr7gymjXbwWVz0gMw
  - UCQSpnDG3YsFNf5-qHocF-WQ
  - UCd_WBvzBg1UbHE8j8MIL5Ng
  - UC4MZ7zUHb5eAxU75Dc_nqdQ
  - UCYyaQsm2HyneP9CsIOdihBw
  - UCGhkRoks9q0Ms7cxpu5gtww
  - UC134rgaltHWHrkYc-R8lkZg
  - UCXu3C3P6ZbpwehPqpZSFYSw
  - UCWsjjgyHya6TDKpZIHW3BrA