notion_api_url: "https://api.notion.com/v1"
notion_token: "${NOTION_TOKEN}" 
notion_database_id: "${NOTION_DATABASE_ID}"
notion_version: "2022-06-28"
YOUTUBE_TOKEN_JSON: "${YOUTUBE_TOKEN_JSON}"
channel_config_file: "channel_config.yaml"
youtube_api_key: "AIzaSyD1v0g2X3x4J6Z5q7Q8e9z5f5f5f5f5f5"
youtube_api_url: "https://www.googleapis.com/youtube/v3"
youtube_api_version: "v3"